config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :cat_rental_requests

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  validates :birth_date, presence: true
  color_options = ["red", "blue", "orange", "black", "white"]
  validates :color, presence: true, inclusion: { in: color_options }
  validates :name, presence: true
  validates :sex, presence: true, inclusion: {in: ["M", "F"]} #%w(M F)

  has_many :cat_rental_requests,
    foreign_key: :cat_id,
    primary_key: :id,
    class_name: 'CatRentalRequest',
    dependent: :destroy

end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :status, presence: true, inclusion: {in: ["PENDING", "APPROVED", "DENIED"]}
  validates :cat_id, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :overlapping_approved_requests
  # TODO validate end_date comes after start_date
  
  belongs_to :cat,
    foreign_key: :cat_id,
    primary_key: :id,
    class_name: 'Cat'


  def overlapping_requests
    CatRentalRequest.where(end_date: start_date..(end_date + 1), cat_id: self.cat_id).where.not(id: self.id)
  end

  def overlapping_approved_requests
    overlaps = overlapping_requests

    if self.status != "APPROVED"
      return true
    elsif overlaps.where(status: "APPROVED").empty?
      return true
    else
      errors[:base].push("PROBLEM WITH RENTING SAME CAT TWICE")
    end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def index
    render text: "Welcome to the Cat Rental Company"
  end

  def new
    @cats = Cat.all
    render :new
  end

  def create
    @new_rental = CatRentalRequest.new(cat_rental_request_params)

    if @new_rental.save
      redirect_to cat_rental_requests_url
    else
      render json: @new_rental.errors.full_messages
    end
  end

  private

  def cat_rental_request_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @new_cat = Cat.new(cat_params)
    if @new_cat.save
      redirect_to cat_url(@new_cat)
    else
      render json: @new_cat.errors.full_messages
    end
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def update
    @cat = Cat.find_by(id: params[:id])
    @cat.update(cat_params) # TODO add if else check

    redirect_to cats_url
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :birth_date, :sex, :color, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_request_helper.rb
module CatRentalRequestHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cat_rental_requests/new.html.erb
<form action="/cat_rental_requests" method="post">

<div>
  <label for cat_rental_request[cat_id]>Rent-a-Cat:</label>
  <select name=cat_rental_request[cat_id]>
  <option ></option>
  <% @cats.each do |cat| %>
    <option value =<%= cat.id %>><%=cat.name %></option>

  <% end %>
</select>
</div>

<div>
  <label for cat_rental_request[start_date]>Check-out:</label>
  <input type= "date" name = cat_rental_request[start_date] />
</div>

<div>
  <label for cat_rental_request[end_date]>Check-in:</label>
  <input type= "date" name = cat_rental_request[end_date] />
</div>

<button type="submit">Submit</button>

</form>

app/views/cats/_form.html.erb
<% action_url = (action == :new) ? cats_url : cat_url(cat) %>

<form action="<%= action_url %>" method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <div>
    <label for cat[name]>Name:</label>
    <input type = "text" name = cat[name] value = "<%= cat.name %>">
  </div>

  <div>
    <label for cat[birth_date]>Birth Date:</label>
    <input type= "date" name = cat[birth_date] value = "<%= cat.birth_date %>"/>
  </div>

  <div>
    <label for cat[sex]>Sex:</label>
    <input type="radio" name = cat[sex] value = "M" <%=checked = "checked" if cat.sex == "M"%> > Male
    <input type="radio" name = cat[sex] value = "F" <%=checked = "checked" if cat.sex == "F"%> > Female
  </div>

  <div>
    <label for cat[color]>Color:</label>
    <select name=cat[color]>
      <option ></option>
      <option value="red" <%=selected = "selected" if cat.color == "red"%> >Red</option>
      <option value="blue" <%=selected = "selected" if cat.color == "blue"%> >Blue</option>
      <option value="orange" <%=selected = "selected" if cat.color == "orange"%> >Orange</option>
      <option value="white" <%=selected = "selected" if cat.color == "white"%> >White</option>
      <option value="black" <%=selected = "selected" if cat.color == "black"%> >Black</option>
    </select>
  </div>

  <div>
    <label for cat[description]>Description:</label><br/>
    <textarea name = cat[description] ><%= cat.description %></textarea>

  </div>

  <button type="submit">Submit</button>
</form>

app/views/cats/edit.html.erb
<%= render "form", cat: @cat, action: :edit %>

app/views/cats/index.html.erb
<title><%= "Cat Names".upcase %></title>

<p><%= "Cat Names".upcase %></p>

<% @cats.each do |cat| %>
  <%= link_to cat.name, cat_url(cat) %>
  <br/>
<% end %>

<%= link_to "Create New Cat", new_cat_url %>

app/views/cats/new.html.erb
<%= render "form", cat: @cat, action: :new %>

app/views/cats/show.html.erb
<p> Welcome to <%= @cat.name%>'s page!</p>

<!-- <% @cat.attributes.each do |key, val| %>
  <%= "#{key.capitalize}: #{val}" unless ["id", "created_at", "updated_at"].include?(key) %>
  <br/>
  <br/>
<% end %> -->

<table>
<% @cat.attributes.each do |key, val| %>
 <% unless ["id", "created_at", "updated_at"].include?(key) %>
    <tr>
      <td><%= "#{key.capitalize}:" %>
      <td><%= "#{val}" %>
    </tr>
  <% end %>
<% end %>

</table>

<!-- TODO add edit button -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cats99Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>